#!/usr/bin/env python
# vim:ts=4:sw=4:tw=0:wm=0:et:foldlevel=99:fileencoding=utf-8:ft=python

NOTES = {
    "GC55J05": "The climb to this one was worse than the find. I parked up the hill about 100' from the turn and climbed the 10' embankment then hiked the 100' to the log containing the cache in plain view. Tupperware with red lid.",
    "GC4HH93": "Park on the dead end road that used to be the main highway; go up the rock path to the right. The cache is a 35mm film canister plainly visible in the rock outcropping.",
    "GC3RANK": "Easy peasy Altoids tin in the guard rail in the second parking lot, second or third vertical from the left end; coordinates good.",
    "GC3RCKG": "Camo container at the base of the sign on the far side of the low water bridge.",
    "GC31H0D": "A centrifuge tube tucked into the ground underneath a large rock next to the utility pole with the tag 2011589.",
    "GC30XE2": "Plastic container just on the far side of the fence; container has hole in it, ants, black mold on the log.",
    "GC48G0X": "35mm film container in hole in the tree.",
    "GC48HVV": "The unseen helper is the tube in which the Old Professor puts his caches; easy find.",
    "GC48HTY": "See the pictures I posted on the cache page. Mickey has been roasted, the log bag burned, the log cut into pieces. Some remnants are to be found in a blue-topped peanut jar at the mouth of the hole in the rock face.",
    "GC5058T": "Easy find in the elf-hole.",
    "GC48ER2": "35mm film canister in the fork of a cedar tree.",
    "GC48AAF": "Cute little honey bear (like Winnie-the-Pooh) in a bag, holding a prescription pill bottle.",
    "GC505A3": "Pill bottle in the leftmost vertical tube of the metal gate.",
    "GC505FN": "Nicely hidden 35mm film canister on the back side of the tree limb that is closest to the road; lightly covered with a piece of bark.",
    "GC503W6": "Easy find - coffee creamer container covered in tape, hanging from a limb about waist high in the tree.",
    "GC58FNZ": "Really easy find - 6 x 8 tupperware container in a black birdhouse.",
    "GC505N9": "Camo'd container in the usual PVC tube next to the sign post.",
    "GC506VH": "'Winchester' box in the end of the guard rail.",
    "GC3G235": "Large pill bottle near a small tree about 3' from the barbed wire fence.",
    "GC506W3": "35mm film canister in the PVC sleeve, camo'd PVC cover, next to utility pole.",
    "GC50C59": "35mm film canister on a wire in the rusted horizontal pipe on the left side of the culvert.",
    "GC507N5": "Smaller white container in larger green prescription bottle right next to cut/fallen tree.",
    "GC50C4R": "35mm film canister in the PVC sleeve, camo'd PVC cover, next to utility pole.",
    "GC509QK": "Go to the fork of the large tree, look for the loop of the wire helper, pull the cache out of the hole.",
    "GC50BNV": "Watch for the '94' dog :-) ; the cache is a 35mm container in the old fence post.",
}
