# vim:ts=4:sw=4:tw=0:wm=0:et:noic

"""Ask for directions in Google Maps

    https://www.google.com/maps/dir/?api=1
"""

########################################################################

from build_path import build_paths
from get_data_from_wpt import get_data_from_wpt
import datetime
import pml
import sys

########################################################################

BOOTSTRAP_LINK = """<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">"""

JQUERY = """<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>"""

BOOTSTRAP = """<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>"""

STYLE = """
table, th, td {
    border: 1px solid black;
    border-collapse: collapse;
    vertical-align: center;
    padding: 3px;
    }
th {
    text-align: center;
    font-size: 125%
    }
h2 {
    text-align: center;
    }
hr {
    border-width: 4px;
}
"""

SCRIPT = """
$(document).ready(function(){
    $(".btn").click(function(){
        $(this).addClass("btn-warning").removeClass("btn-primary");
    });
    $("#bobs_reset").click(function(){
        $(".btn-warning").addClass("btn-primary").removeClass("btn-warning");
    });
});
"""

########################################################################


def directions(
    lats=None,
    lons=None,
    start=None,
    end=None,
    waypoints=None
):
    """Create URI for a map from 'start' to 'end' via possibly empty
'waypoints' list of intermediate points"""

    result = "https://www.google.com/maps/dir/?api=1"
    result += "&origin=%s,%s" % (lats[start], lons[start])
    result += "&destination=%s,%s" % (lats[end], lons[end])
    if waypoints:
        waypoints_string = "&waypoints="
        for index, wpt in enumerate(waypoints):
            if index != 0:
                waypoints_string += "%7C"
            waypoints_string += "%s,%s" % (lats[wpt], lons[wpt])
        result += waypoints_string
    return result

########################################################################


def build_map_table_html(data):
    """Create a HTML file containing a table of links to maps for each segment
of the route going from geocache to geocache."""

    lats, lons, texts, syms, names, usersorts, hrefs = zip(*data)

    doc = pml.XHTML("html")
    today = datetime.date.today()
    doc.title(f"Generated by {__file__} on {today}.")
    doc.meta(charset="utf-8")
    doc.meta(name="viewport", content="width=device-width, initial-scale=1")
    doc += BOOTSTRAP_LINK
    doc += JQUERY
    doc += BOOTSTRAP
    doc.style(STYLE)
    doc.script(SCRIPT)

    doc.body.h2(f"Created {today} by {__file__}.")
    doc.body.hr()

    div = doc.body.div(klass="container")
    div.h2("Table of Map Routes")
    table = div.table(klass="table")

    thead = table.thead()
    tr = thead.tr()
    tr.th("Link", colspan="1")
    tr.th("Waypoints", colspan="2")

    tr = thead.tr()
    tr.th("To: UserSort")
    tr.th("Name")
    tr.th("Via Names")

    tbody = table.tbody()

    for item_index, items in enumerate(build_paths(data)):
        start, end, waypoints = items

        # show phony header row just for route starting point
        if item_index == 0:
            tr = tbody.tr()
            tr.td.button(
                "Reset: %s" % usersorts[start],
                klass="btn btn-primary",
                id="bobs_reset"
            )
            tr.td(texts[start])
            tr.td()

        tr = tbody.tr()
        href = directions(
            lats=lats,
            lons=lons,
            start=start,
            end=end,
            waypoints=waypoints
        )
        td = tr.td.a(
            "%s" % (usersorts[end]),
            href=href,
            target="_blank",
            type="button",
            klass="btn btn-primary"
        )

        if hrefs[end]:
            tr.td.a(
                texts[end],
                href=hrefs[end],
                target="_blank"
            )
        else:
            tr.td(texts[end])

        td3 = tr.td()
        if waypoints:
            for index, waypoint in enumerate(waypoints):
                if index != 0:
                    td3.br()
                td3 += texts[waypoint]

    return "<!DOCTYPE HTML>\n" + str(doc)

########################################################################


if __name__ == "__main__":

    from json import loads

    json_filename = "outfile.json"
    print(f"Reading from {json_filename}", file=sys.stderr)

    with open(json_filename, "rb") as jsonfile:
        doc = loads(jsonfile.read())

    print(build_map_table_html(
        get_data_from_wpt(doc["gpx"]["wpt"])
    ))

# end of file
